trigger:
  branches:
    include:
      - master
  paths:
    include:
      - service-a/**

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: dockerHub
  imageRepository: saurabhdhande/service-a
  dockerfilePath: $(Build.SourcesDirectory)/service-a/Dockerfile
  buildContext: $(Build.SourcesDirectory)/service-a
  imageTag: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and push service-a image
    jobs:
      - job: DockerBuildPush
        displayName: Build and push Docker image
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and push service-a
            inputs:
              command: buildAndPush
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              buildContext: $(buildContext)
              tags: |
                $(imageTag)
                latest
